# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "catamaran"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_catamaran_faceFloatWall_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 200.0000, 0)
	P001 = App.Vector(23.1342, 91.2399, 0)
	P002 = App.Vector(88.5313, 1.3111, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(89.5613, 1.1222, 0)
	P004 = App.Vector(90.1951, 1.9559, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(97.5473, 100.8567, 0)
	P006 = App.Vector(100.0000, 200.0000, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(100.0000, 800.0000, 0)
	S003 = Part.LineSegment(P006, P007)
	P008 = App.Vector(97.5473, 899.1433, 0)
	P009 = App.Vector(90.1951, 998.0441, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(89.5613, 998.8778, 0)
	P011 = App.Vector(88.5313, 998.6889, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(23.1342, 908.7601, 0)
	P013 = App.Vector(0.0000, 800.0000, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(0.0000, 200.0000, 0)
	S007 = Part.LineSegment(P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_catamaran_faceFloatWall_Fa0_Ctr1():
	P000 = App.Vector(2.0000, 200.0000, 0)
	P001 = App.Vector(23.3491, 96.1510, 0)
	P002 = App.Vector(83.9337, 9.1458, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(87.0508, 8.5108, 0)
	P004 = App.Vector(88.9864, 11.0353, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(95.7453, 105.4102, 0)
	P006 = App.Vector(98.0000, 200.0000, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(98.0000, 800.0000, 0)
	S003 = Part.LineSegment(P006, P007)
	P008 = App.Vector(95.7453, 894.5898, 0)
	P009 = App.Vector(88.9864, 988.9647, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(87.0508, 991.4892, 0)
	P011 = App.Vector(83.9337, 990.8542, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(23.3491, 903.8490, 0)
	P013 = App.Vector(2.0000, 800.0000, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(2.0000, 200.0000, 0)
	S007 = Part.LineSegment(P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_catamaran_faceFloatWall_Fa0():
	FC000 = ctr_face_catamaran_faceFloatWall_Fa0_Ctr0()
	FC001 = ctr_face_catamaran_faceFloatWall_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_catamaran_faceFloatWall_Fa1_Ctr0():
	P000 = App.Vector(300.0000, 200.0000, 0)
	P001 = App.Vector(302.4527, 100.8567, 0)
	P002 = App.Vector(309.8049, 1.9559, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(310.4387, 1.1222, 0)
	P004 = App.Vector(311.4687, 1.3111, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(376.8658, 91.2399, 0)
	P006 = App.Vector(400.0000, 200.0000, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(400.0000, 800.0000, 0)
	S003 = Part.LineSegment(P006, P007)
	P008 = App.Vector(376.8658, 908.7601, 0)
	P009 = App.Vector(311.4687, 998.6889, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(310.4387, 998.8778, 0)
	P011 = App.Vector(309.8049, 998.0441, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(302.4527, 899.1433, 0)
	P013 = App.Vector(300.0000, 800.0000, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(300.0000, 200.0000, 0)
	S007 = Part.LineSegment(P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_catamaran_faceFloatWall_Fa1_Ctr1():
	P000 = App.Vector(302.0000, 200.0000, 0)
	P001 = App.Vector(304.2547, 105.4102, 0)
	P002 = App.Vector(311.0136, 11.0353, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(312.9492, 8.5108, 0)
	P004 = App.Vector(316.0663, 9.1458, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(376.6509, 96.1510, 0)
	P006 = App.Vector(398.0000, 200.0000, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(398.0000, 800.0000, 0)
	S003 = Part.LineSegment(P006, P007)
	P008 = App.Vector(376.6509, 903.8490, 0)
	P009 = App.Vector(316.0663, 990.8542, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(312.9492, 991.4892, 0)
	P011 = App.Vector(311.0136, 988.9647, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(304.2547, 894.5898, 0)
	P013 = App.Vector(302.0000, 800.0000, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(302.0000, 200.0000, 0)
	S007 = Part.LineSegment(P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_catamaran_faceFloatWall_Fa1():
	FC000 = ctr_face_catamaran_faceFloatWall_Fa1_Ctr0()
	FC001 = ctr_face_catamaran_faceFloatWall_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def catamaran_faceFloatWall():
	FA000 = face_catamaran_faceFloatWall_Fa0()
	FA001 = face_catamaran_faceFloatWall_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_catamaran_faceFloatBase_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 200.0000, 0)
	P001 = App.Vector(23.1342, 91.2399, 0)
	P002 = App.Vector(88.5313, 1.3111, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(89.5613, 1.1222, 0)
	P004 = App.Vector(90.1951, 1.9559, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(97.5473, 100.8567, 0)
	P006 = App.Vector(100.0000, 200.0000, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(100.0000, 800.0000, 0)
	S003 = Part.LineSegment(P006, P007)
	P008 = App.Vector(97.5473, 899.1433, 0)
	P009 = App.Vector(90.1951, 998.0441, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(89.5613, 998.8778, 0)
	P011 = App.Vector(88.5313, 998.6889, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(23.1342, 908.7601, 0)
	P013 = App.Vector(0.0000, 800.0000, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(0.0000, 200.0000, 0)
	S007 = Part.LineSegment(P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_catamaran_faceFloatBase_Fa0():
	FC000 = ctr_face_catamaran_faceFloatBase_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_catamaran_faceFloatBase_Fa1_Ctr0():
	P000 = App.Vector(300.0000, 200.0000, 0)
	P001 = App.Vector(302.4527, 100.8567, 0)
	P002 = App.Vector(309.8049, 1.9559, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(310.4387, 1.1222, 0)
	P004 = App.Vector(311.4687, 1.3111, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(376.8658, 91.2399, 0)
	P006 = App.Vector(400.0000, 200.0000, 0)
	S002 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(400.0000, 800.0000, 0)
	S003 = Part.LineSegment(P006, P007)
	P008 = App.Vector(376.8658, 908.7601, 0)
	P009 = App.Vector(311.4687, 998.6889, 0)
	S004 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(310.4387, 998.8778, 0)
	P011 = App.Vector(309.8049, 998.0441, 0)
	S005 = Part.Arc(P009, P010, P011)
	P012 = App.Vector(302.4527, 899.1433, 0)
	P013 = App.Vector(300.0000, 800.0000, 0)
	S006 = Part.Arc(P011, P012, P013)
	P014 = App.Vector(300.0000, 200.0000, 0)
	S007 = Part.LineSegment(P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_catamaran_faceFloatBase_Fa1():
	FC000 = ctr_face_catamaran_faceFloatBase_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def catamaran_faceFloatBase():
	FA000 = face_catamaran_faceFloatBase_Fa0()
	FA001 = face_catamaran_faceFloatBase_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_catamaran_faceCabineBase_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 200.0000, 0)
	P001 = App.Vector(400.0000, 200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(400.0000, 800.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 800.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 200.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_catamaran_faceCabineBase_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(200.0000, 242.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_catamaran_faceCabineBase_Fa0():
	FC000 = ctr_face_catamaran_faceCabineBase_Fa0_Ctr0()
	FC001 = ctr_face_catamaran_faceCabineBase_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def catamaran_faceCabineBase():
	FA000 = face_catamaran_faceCabineBase_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_catamaran_faceCabineWall_Fa0_Ctr0():
	P000 = App.Vector(200.0000, 120.0000, 0)
	P001 = App.Vector(800.0000, 120.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.0000, 160.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(650.0000, 260.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(350.0000, 260.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(200.0000, 160.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(200.0000, 120.0000, 0)
	S005 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_catamaran_faceCabineWall_Fa0():
	FC000 = ctr_face_catamaran_faceCabineWall_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def catamaran_faceCabineWall():
	FA000 = face_catamaran_faceCabineWall_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_catamaran_faceCabineEnv_Fa0_Ctr0():
	P000 = App.Vector(200.0000, 120.0000, 0)
	P001 = App.Vector(202.0000, 120.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(202.0000, 158.9296, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(351.1094, 258.3359, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(350.0000, 260.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(200.0000, 160.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(200.0000, 120.0000, 0)
	S005 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_catamaran_faceCabineEnv_Fa0():
	FC000 = ctr_face_catamaran_faceCabineEnv_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_catamaran_faceCabineEnv_Fa1_Ctr0():
	P000 = App.Vector(800.0000, 120.0000, 0)
	P001 = App.Vector(798.0000, 120.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(798.0000, 158.9296, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(648.8906, 258.3359, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(650.0000, 260.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(800.0000, 160.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(800.0000, 120.0000, 0)
	S005 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_catamaran_faceCabineEnv_Fa1():
	FC000 = ctr_face_catamaran_faceCabineEnv_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def catamaran_faceCabineEnv():
	FA000 = face_catamaran_faceCabineEnv_Fa0()
	FA001 = face_catamaran_faceCabineEnv_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_catamaran_faceVault_Fa0_Ctr0():
	P000 = App.Vector(100.0000, 95.0000, 0)
	P001 = App.Vector(107.3223, 112.6777, 0)
	P002 = App.Vector(125.0000, 120.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(125.0000, 122.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(98.0000, 122.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(98.0000, 95.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(100.0000, 95.0000, 0)
	S004 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_catamaran_faceVault_Fa0():
	FC000 = ctr_face_catamaran_faceVault_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_catamaran_faceVault_Fa1_Ctr0():
	P000 = App.Vector(300.0000, 95.0000, 0)
	P001 = App.Vector(292.6777, 112.6777, 0)
	P002 = App.Vector(275.0000, 120.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(275.0000, 122.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(302.0000, 122.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(302.0000, 95.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(300.0000, 95.0000, 0)
	S004 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_catamaran_faceVault_Fa1():
	FC000 = ctr_face_catamaran_faceVault_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def catamaran_faceVault():
	FA000 = face_catamaran_faceVault_Fa0()
	FA001 = face_catamaran_faceVault_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def fex_subpax_catamaran_floatB():
	FIG = catamaran_faceFloatBase()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_catamaran_floatB = fex_subpax_catamaran_floatB()

def fex_subpax_catamaran_floatW():
	FIG = catamaran_faceFloatWall()
	VEX = FIG.extrude(App.Vector(0, 0, 120))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_catamaran_floatW = fex_subpax_catamaran_floatW()

def fex_subpax_catamaran_cabineB():
	FIG = catamaran_faceCabineBase()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 120.0000))
	return VFP
subpax_catamaran_cabineB = fex_subpax_catamaran_cabineB()

def fex_subpax_catamaran_cabineW1():
	FIG = catamaran_faceCabineWall()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_catamaran_cabineW1 = fex_subpax_catamaran_cabineW1()

def fex_subpax_catamaran_cabineW2():
	FIG = catamaran_faceCabineWall()
	VEX = FIG.extrude(App.Vector(0, 0, 2))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(398.0000, 0.0000, 0.0000))
	return VFP
subpax_catamaran_cabineW2 = fex_subpax_catamaran_cabineW2()

def fex_subpax_catamaran_cabineEnv():
	FIG = catamaran_faceCabineEnv()
	VEX = FIG.extrude(App.Vector(0, 0, 400))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_catamaran_cabineEnv = fex_subpax_catamaran_cabineEnv()

def fex_subpax_catamaran_vault():
	FIG = catamaran_faceVault()
	VEX = FIG.extrude(App.Vector(0, 0, 600))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 800.0000, 0.0000))
	return VFP
subpax_catamaran_vault = fex_subpax_catamaran_vault()

def fvol_pax_catamaran():
	V000 = subpax_catamaran_floatB
	V001 = V000.fuse(subpax_catamaran_floatW)
	V002 = V001.fuse(subpax_catamaran_cabineB)
	V003 = V002.fuse(subpax_catamaran_cabineW1)
	V004 = V003.fuse(subpax_catamaran_cabineW2)
	V005 = V004.fuse(subpax_catamaran_cabineEnv)
	V006 = V005.fuse(subpax_catamaran_vault)
	VFC = V006.removeSplitter()
	return VFC
pax_catamaran = fvol_pax_catamaran()


pax_catamaran.check()
#pax_catamaran.exportBrep(f"{outFileName}.brep")
#pax_catamaran.exportIges(f"{outFileName}.igs")
#pax_catamaran.exportStep(f"{outFileName}.stp")
pax_catamaran.exportStl(f"{outFileName}.stl")

